# Generated by Django 5.2.1 on 2025-05-18 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentagency',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
