# Generated by Django 5.2.1 on 2025-05-18 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_management', '0002_governmentagency_assigned_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governmentagency',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='governmentagency',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
